### PR TITLE
Support multiple source contexts per binary

### PR DESCRIPTION
**Pull request by gnidan**
Part of #39 

- Remove the `context` app module and move its responsibilities by (beginning to) normalize the state shape. (Ref: [relevant Redux docs](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape))

- Work towards dividing app-module states into standard `proc` and `info` (for runtime info, start-time info, respectively)

- Define and utilize various "state models":
  - **evm.info.contexts** to represent bytecodes
  - **evm.info.instances** to link bytecode to address
  - **solidity.info.sources** to represent source/AST/etc.
  - **solidity.info.sourceMaps** to link bytecode to one or more sources
  - **data.info.scopes** to represent variable information about AST nodes
  - **data.proc.assignments** to maintain references to stack/memory/storage for each variable

- Flatten `data` state so as not to maintain separate records for each source.

- Add `files` option to Debugger constructor, to identify file indexes referenced in sourcemaps/ASTs

_**N.B.** this now forces the pre-condition that file indexes and AST node IDs are unique._

### CODE REVIEW

**Comment by gnidan** [comment]
Resulting dependency graph:
deps

**Comment by cgewecke** [comment]
Looks nice!! 
> N.B. this now forces the pre-condition that file indexes and AST node IDs are unique.

Does this mean that even if you could do something clever with the file ids, the node id uniqueness problem is overwhelming - i.e realistically fresh compilation is necessary for debugging? (Which seems normal to me fwiw).

**Comment by gnidan** [comment]
Thanks @cgewecke!

> Does this mean that even if you could do something clever with the file ids, the node id uniqueness problem is overwhelming

Basically -___-

**Comment by gnidan** [comment]
@cgewecke should this go out with 4.1.4?

**Comment by cgewecke** [comment]
@gnidan Yeah! Totally.

**Pull request merged**
